name: core_kit_lints
description: Lint rules for core_kit.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  analyzer:  
  custom_lint:  
  custom_lint_builder:  
  path: any
