name: core_kit_lints
description: Lint rules for core_kit.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  custom_lint: ^2.1.0
  custom_lint_builder: ^2.1.0
  path: any
